# For more information: https://laravel.com/docs/sail
version: "3"
services:
  app_imgproxy:
    image: "node:18.12-bullseye"
    container_name: app_imgproxy
    hostname: app_imgproxy
    restart: always
    ports:
      - '${APP_PORT:-8080}:8080'
      - '${DEBUG_PORT:-9229}:9229'
    environment:
      APP_URL: '${APP_URL:-http://localhost:8080}'
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      - './:/home/app'
    working_dir: /home/app
    entrypoint: [ "tail", "-f", "/dev/null" ]

  imgproxy:
    image: "darthsim/imgproxy"
    container_name: imgproxy
    hostname: imgproxy
    volumes:
      - './media:/media'
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /media
      IMGPROXY_MAX_SRC_RESOLUTION: "9999"
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
