version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    container_name: app_imgproxy
    hostname: app_imgproxy
    ports:
      - '${APP_PORT:-8080}:8080'
    environment:
      APP_URL: '${APP_URL:-http://localhost:8080}'
    volumes:
      - './media:/home/app/media'
      - './cache:/home/app/cache'

  imgproxy:
    image: "darthsim/imgproxy"
    container_name: imgproxy
    hostname: imgproxy
    restart: always
    environment:
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /media
      IMGPROXY_MAX_SRC_RESOLUTION: "9999"
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
